name: 'Slack Notifications'
description: 'Greet someone and record the time'
inputs:
  incoming-webhook-url:
    description: 'The incoming webhook URL for the slack organisation'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
